# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
  config.before do
    p1 = Person.create(first_name: 'Kelvin', last_name: 'Martin')
    p2 = Person.create(first_name: 'Al',     last_name: 'Capone')
    p3 = Person.create(first_name: 'John',   last_name: 'Dillinger')
    p4 = Person.create(first_name: 'Jon',   last_name: 'Grover')

    [
      {incident_type: 'Armed Robbery'},
      {incident_type: 'First Degree Murder'}
    ].each do |ch_hash|
      p1.criminal_histories.create(ch_hash)
    end

    [
      {incident_type: 'Income Tax Evasion'},
      {incident_type: 'Violation of the Volstead Act'}
    ].each do |ch_hash|
      p2.criminal_histories.create(ch_hash)
    end

    [
      {incident_type: 'Armed Robbery'},
      {incident_type: 'Manslaughter'},
      {incident_type: 'First Degree Murder'}
    ].each do |ch_hash|
      p3.criminal_histories.create(ch_hash)
    end

    [
      {incident_type: 'Being Way Too Fly'},
      {incident_type: 'Using AJAX Without a License'},
      {incident_type: 'Pollywog Fighting'}
    ].each do |ch_hash|
      p4.criminal_histories.create(ch_hash)
    end

    f1 = p1.fingerprints.create
    f2_fbi = p2.fingerprints.create
    f2_cpd = p2.fingerprints.create
    f3 = p3.fingerprints.create
    f4 = p4.fingerprints.create

    f1.create_fingerprint_database(name: 'Criminal Fingerprints', owner: 'New York Police Department')
    f2_fbi.create_fingerprint_database(name: 'Most Wanted List', owner: 'Federal Bureau of Investigations')
    f2_cpd.create_fingerprint_database(name: 'Fingerprints of Criminals', owner: 'Chicago Police Department')
    f3.create_fingerprint_database(name: 'Bandits and Outlaws', owner: 'Federal Bureau of Investigations')
    f4.create_fingerprint_database(name: 'Flatiron School', owner: 'Central Intelligence Agency')
  end
end
